name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote add space https://huggingface.co/spaces/bipinsaha/chatPDF
          git fetch space --prune --unshallow

      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push space main
